buildVariable: false
familyName: Noto Sans Egyptian Hieroglyphs
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansEgyptianHieroglyphs.designspace
